version: "3.8"

services:
  app:
    build: .
    container_name: curvvtech
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=Curvvtech
      - JWT_REFRESH_SECRET=CurvvtechRef
      - MONGO_URI=mongodb://mongo:27017/curvvtech
      - REDIS_DB_USERNAME=default
      - REDIS_DB_HOST=localhost
      - REDIS_DB_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
